# Change these first
owner: jacobfernandez917 # Your GitHub organization or username, where this repository lives
repo: concati-dokploy-upptime # The name of this repository

sites:
  - name: Fraudster Identification
    url: http://52.76.231.243:5000
  - name: OTP + Number Verification
    url: http://52.76.231.243:5001
  - name: Device Authentication API
    url: http://52.76.231.243:5003
  - name: Device Authentication Frontend
    url: http://52.76.231.243:5005

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /concati-dokploy-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Concati Dokploy Upptime
  introTitle: "**Containers Uptime Monitoring**"
  introMessage: This is for monitoring the uptime status of containers deployed on Dokploy
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
