# Change these first
owner: jacobfernandez917 # Your GitHub organization or username, where this repository lives
repo: concati-dokploy-upptime # The name of this repository

sites:
  - name: Caller ID API
    url: http://52.76.231.243:10043
  - name: Consent Management API
    url: http://52.76.231.243:10042
  - name: Device Identifier API
    url: http://52.76.231.243:5008
  - name: Device Status API
    url: http://52.76.231.243:5007
  - name: Device Status API - B
    url: http://52.76.231.243:10039
  - name: Device Swap API
    url: http://52.76.231.243:5006
  - name: Device Swap API - B
    url: http://52.76.231.243:10038
  - name: eSIM Provisioning API
    url: http://52.76.231.243:10024
  - name: Fraudster Blacklist History API
    url: http://52.76.231.243:10015
  - name: Fraudster Bulk Reporting API
    url: http://52.76.231.243:10013
  - name: Fraudster Identification API
    url: http://52.76.231.243:5000
  - name: Fraudster Investigation Feedback API
    url: http://52.76.231.243:10016
  - name: Fraudster MSISDN Check API
    url: http://52.76.231.243:10011
  - name: Fraudster MSISDN Submission API
    url: http://52.76.231.243:10012
  - name: Fraudster Spam Number Verification API
    url: http://52.76.231.243:10014
  - name: GeoScores API
    url: http://52.76.231.243:10020
  - name: GeoScores Frontend
    url: http://52.76.231.243:10021
  - name: Location Insights API
    url: http://52.76.231.243:5010
  - name: Location Insights API - B
    url: http://52.76.231.243:10041
  - name: Number Verification API
    url: http://52.76.231.243:10028
  - name: OTP + Number Verification API
    url: http://52.76.231.243:5001
  - name: OTP + Number Verification - B
    url: http://52.76.231.243:10037
  - name: Quality on Demand API
    url: http://52.76.231.243:5009
  - name: Swim Swap API
    url: http://52.76.231.243:10027
assignees: # Users to assign downtime issues (optional)
  - jacobfernandez917
  - jerwyn917
  - zfmanalang
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /concati-dokploy-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Concati Dokploy Upptime
  introTitle: "**Containers Uptime Monitoring**"
  introMessage: This is for monitoring the uptime status of containers deployed on Dokploy
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
